### ISSUE TITLE
AttributeError: 'Row' object has no attribute 'style'

### ISSUE THREAD

**Issue by tralala87** [camenduru/AnimateDiff-colab#12]
When running and of the two motion_lora colabs I get:

Traceback (most recent call last):
  File "/content/animatediff/app.py", line 338, in <module>
    demo = ui()
  File "/content/animatediff/app.py", line 294, in ui
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

**Comment by AngelTs** [comment]
Replace "!pip install gradio einops ..." with "!pip install gradio==3.41.2 einops ..."
