### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for CLIPTextModel:

### ISSUE THREAD

**Issue by AIculture** [camenduru/AnimateDiff-colab#4]
All the colab notebooks stopped working 07/18 and return the same issue.
Not sure exactly what triggered the issue but all animateDiff colab notebooks return the same issue when running last cell:

RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
	Unexpected key(s) in state_dict: "text_model.embeddings.position_ids". 

here's the full thing: 

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/AnimateDiff/scripts/animate.py", line 176, in <module>
    main(args)
  File "/content/AnimateDiff/scripts/animate.py", line 99, in main
    pipeline.text_encoder = convert_ldm_clip_checkpoint(base_state_dict)
  File "/content/AnimateDiff/animatediff/utils/convert_from_ckpt.py", line 726, in convert_ldm_clip_checkpoint
    text_model.load_state_dict(text_model_dict)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
	Unexpected key(s) in state_dict: "text_model.embeddings.position_ids".

Any idea?

**Comment by camenduru** [comment]
maybe something broke with the new colab update 😐 I will check

**Comment by camenduru** [comment]
maybe fixed please try again 
thanks to @geeky-zeeshan ❤ https://github.com/guoyww/AnimateDiff/issues/57#issuecomment-1642102767
