### ISSUE TITLE
5-RealisticVision.yaml points to a wrong safetensor

### ISSUE THREAD

**Issue by elBlacksmith** [camenduru/AnimateDiff-colab#6]
I think that the Realistic Vision YAML is bugged.

It points to "realisticVisionV20_v20.safetensors" but the first cell creates a file called "realisticVisionV40_v20Novae.safetensors"

So, I get this error, when I unselect the default model and  prompt file on the Colab:

```
/content/animatediff
2023-07-24 20:44:41.657011: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
loaded temporal unet's pretrained weights from /content/animatediff/models/StableDiffusion/unet ...
### missing keys: 560; 
### unexpected keys: 0;
### Temporal Module Parameters: 417.1376 M
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/animatediff/scripts/animate.py", line 159, in <module>
    main(args)
  File "/content/animatediff/scripts/animate.py", line 78, in main
    with safe_open(model_config.path, framework="pt", device="cpu") as f:
FileNotFoundError: No such file or directory: "models/DreamBooth_LoRA/realisticVisionV20_v20.safetensors"
```

I made the change of filename by myself and it has generated a couple of gifs.

**Comment by camenduru** [comment]
Hi @elBlacksmith 👋 thanks for the info ❤ please try again
